module.exports = {
  apps: [
    {
      name: "aw-web",
      script: "bun",
      args: "run start",
      cwd: "/var/www/accessories-world/apps/web",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      exec_mode: "cluster",
      instances: 2,
      max_memory_restart: "500M",
      error_file: "/var/log/pm2/aw-web-error.log",
      out_file: "/var/log/pm2/aw-web-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "aw-admin",
      script: "bun",
      args: "run start",
      cwd: "/var/www/accessories-world/apps/admin",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      exec_mode: "cluster",
      instances: 2,
      max_memory_restart: "500M",
      error_file: "/var/log/pm2/aw-admin-error.log",
      out_file: "/var/log/pm2/aw-admin-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "aw-wholesalers",
      script: "bun",
      args: "run start",
      cwd: "/var/www/accessories-world/apps/wholesalers",
      env: {
        NODE_ENV: "production",
        PORT: 3002,
      },
      exec_mode: "cluster",
      instances: 2,
      max_memory_restart: "500M",
      error_file: "/var/log/pm2/aw-wholesalers-error.log",
      out_file: "/var/log/pm2/aw-wholesalers-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "aw-server",
      script: "bun",
      args: "run start",
      cwd: "/var/www/accessories-world/apps/server",
      env: {
        NODE_ENV: "production",
        PORT: 3003,
      },
      exec_mode: "fork",
      instances: 1,
      max_memory_restart: "500M",
      error_file: "/var/log/pm2/aw-server-error.log",
      out_file: "/var/log/pm2/aw-server-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "aw-agent",
      script: "bun",
      args: "run start",
      cwd: "/var/www/accessories-world/apps/agent",
      env: {
        NODE_ENV: "production",
        PORT: 3004,
      },
      exec_mode: "fork",
      instances: 1,
      max_memory_restart: "500M",
      error_file: "/var/log/pm2/aw-agent-error.log",
      out_file: "/var/log/pm2/aw-agent-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "aw-blog",
      script: "bunx",
      args: "astro preview --host 0.0.0.0",
      cwd: "/var/www/accessories-world/apps/blog",
      env: {
        NODE_ENV: "production",
        PORT: 4321,
      },
      exec_mode: "fork",
      instances: 1,
      max_memory_restart: "300M",
      error_file: "/var/log/pm2/aw-blog-error.log",
      out_file: "/var/log/pm2/aw-blog-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],

  // Global configuration
  name: "accessories-world",
  merge_logs: false,
  autorestart: true,
  watch: false,
  ignore_watch: ["node_modules", ".git", "dist", ".next", "build"],
  max_restarts: 10,
  min_uptime: 10000,
};
